package dev.duma.android.sunmi.scanconfigurationhelper.config.enums;

public enum ConfigurationFieldEnum {
    OutputEncodingCode,
    VirtualFloatingScanButton,
    Beep,
    Vibrate,
    TriggerMethod,
    ScanTriggerTimeOut,
    TriggerOverTime,
    TriggerContinuousTime,
    ScanResultCodeID,
    Prefix,
    Suffix,
    OutputBroadcastEnabled,
    OutputBroadcastAction,
    OutputBroadcastDataKey,
    OutputBroadcastByteKey,
    OutputBroadcastStartAction,
    OutputBroadcastEndAction,
    OutputType,
    AddTab,
    AddReturn,
    AsEvents,
    AddSpace,
    OutputCharacterInterval,
    AdvancedFormatEnabled,
    AdvancedFormat,
    CenterFlagScan,
    Flash,
    Scene,
    RemoveGroupSeparator,
    PrefixCharactersRemoved,
    SuffixCharactersRemoved,
}
